platform :ios, '11.0'
inhibit_all_warnings!

target 'NSFKit_Example' do
  pod 'NSFKit', :path => '../'

  target 'NSFKit_Tests' do
# https://github.com/CocoaPods/CocoaPods/issues/5383#issuecomment-220633840
#    inherit! :search_paths
    pod 'NSFKit', :path => '../'

    pod 'Quick', :inhibit_warnings => true
    pod 'Nimble'
  end
end


post_install do |installer|
      
  pods_project = installer.pods_project
  deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
  deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
  minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }
  
  puts 'Minimal deployment target is ' + minimal_deployment_target
  puts 'Setting each pod deployment target to ' + minimal_deployment_target
  
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings[deployment_target_key] = minimal_deployment_target
      end
  end
  
  installer.pods_project.build_configurations.each do |config|
      if config.name == 'Release'
          config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
      end
  end
  
  puts 'Setting pod project swift version'
  
  pods_project.targets.each do |target|
      if ['ReactiveCocoa'].include? target.name then
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '5.0'
          end
      else
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '5.0'
          end
      end
  end
end

